ALTER TABLE reviews
ALTER COLUMN name VARCHAR(50);

ALTER TABLE reviews
ALTER COLUMN email VARCHAR(50);

ALTER TABLE reviews
ALTER COLUMN product VARCHAR(50);

ALTER TABLE reviews
ALTER COLUMN comment VARCHAR(50);


